defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  database: gemwish_dev
  <<: *defaults

test:
  database: gemwish_test
  <<: *defaults

production:
  database: gemwish
  <<: *defaults
